package foodtruckfrenzy;

public enum DrawableEnum {
    FOODTRUCK_UP,
    FOODTRUCK_DOWN,
    FOODTRUCK_LEFT,
    FOODTRUCK_RIGHT,
    COP_UP,
    COP_DOWN,
    COP_LEFT,
    COP_RIGHT,
    OBSTRUCTION,
    SPEED_TRAP,
    POT_HOLE,
    FOOD,

    HORIZONTAL_ROAD,
    VERTICAL_ROAD,
    FOUR_WAY_INTERSECT,

    NORTH_WEST_CORNER,
    NORTH_EAST_CORNER,
    SOUTH_EAST_CORNER,
    SOUTH_WEST_CORNER,

    NORTH_THREE_WAY,
    EAST_THREE_WAY,
    SOTUH_THREE_WAY,
    WEST_THREE_WAY

}

